### ISSUE TITLE
Unable to run listen command: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by ricardoduarte** [Opus10/django-pgpubsub#21]
I followed the example in the docs in an existing Django project. I can run Django server okay but exery time I try to run `listen` command I'm getting the following error:
```
root@23aaf9ba7e4c:/app# python manage.py listen
Listening on submissions.channels.SubmissionGroupClones
Process pgpubsub_process_0:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/pgpubsub/listen.py", line 25, in listen
    pg_connection = listen_to_channels(channels)
  File "/usr/local/lib/python3.9/site-packages/pgpubsub/listen.py", line 62, in listen_to_channels
    cursor.execute(f'LISTEN {channel.listen_safe_name()};')
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
I've made sure I ran `makemigrations` and  `migrate` command and added `pgpubsub` and `pgtrigger` to the installed apps. Need some help trying to figuring out what I'm possibly doing wrong here.

My environment (I'm running my application via Docker):

- Python 3.9
- Django 3.2.5
- Postgres 13

docker-compose.yml
```
version: '3'

services:
  web:
    container_name: pack4sustain-web
    build:
      context: .
    command: ./devops/wait.sh python manage.py runserver 0.0.0.0:8000 --insecure
    env_file: pack4sustain/settings/.env
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    container_name: pack4sustain-worker
    build:
      context: .
    command: ./devops/wait.sh python manage.py listen
    env_file: pack4sustain/settings/.env
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
    depends_on:
      - db

  test:
    container_name: pack4sustain-test
    build:
      context: .
    command: ./devops/wait.sh pytest
    environment:
      - DJANGO_ENV=test
      - DJANGO_SETTINGS_MODULE=pack4sustain.settings.test
      - DATABASE_URL=postgres://pack4sustain:pack4sustain@db/pack4sustain_test
      - PGUSER=pack4sustain
      - PGPASSWORD=pack4sustain
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=pack4sustain_test
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: pack4sustain-db
    environment:
      - POSTGRES_USER=pack4sustain
      - POSTGRES_PASSWORD=pack4sustain
      - POSTGRES_DB=pack4sustain_dev
      # Set a path where Postgres should store the data
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
      - ./db_dumps:/db_dumps
      - ./devops/create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh
    ports:
      - "5432:5432"
```

channels.py
```
from dataclasses import dataclass

from pgpubsub.channel import Channel


@dataclass
class SubmissionGroupClones(Channel):
    original_submission_group_id: int
    new_submission_group_id: int
```

listeners.py
```
import pgpubsub

from submissions.channels import SubmissionGroupClones


@pgpubsub.listener(SubmissionGroupClones)
def clone_submissions_from_submission_group(original_submission_group_id: int, new_submission_group_id: int):
    print("executed clone_submissions_from_submissions_group")
```

Any help would be really appreciated. If you need more relevant information, please let me know.

**Comment by PaulGilmartin** [comment]
@ricardoduarte Hmm, weird. It looks like the connection to postgres isn't working for some reason. Are you able to connect to the database at all? For example, if you run
```
root@23aaf9ba7e4c:/app# python manage.py shell
```
and then perform a query to the database, does it work as expected? What about if you  run the following in a shell?
```
from django.db import connection
cursor = connection.cursor()
cursor.execute('LISTEN test;')
```

**Comment by ricardoduarte** [comment]
Hello @PaulGilmartin 

Thanks for the response and sorry for the delay on testing this. Did the test you suggested and it wen fine.
![image](https://user-images.githubusercontent.com/809712/215764136-9bdb16ef-e174-4d51-ace5-6f5c6c497cb4.png)

Another weird stuff (don't know if it is related to the main problem) is when I run both containers via `docker-compose` it says that I have migrations to create, but when I run `makemigrations` command it creates the same migration already existing and therefore there is nothing new to apply when I run again `migrate`.

Also, the we container runs without any error, while the other one...
![image](https://user-images.githubusercontent.com/809712/215765458-c9033d63-0f49-47b9-8d31-d4653702e84d.png)

**Comment by ricardoduarte** [comment]
@PaulGilmartin I'm using only one postgres instance.

When I run `makemigrations`  command, it always create the same file. The proof is when I run `migrate`, it finds nothing to apply.
![image](https://user-images.githubusercontent.com/809712/215848735-d5d59ae2-9fd6-4e20-8a85-b0ff2905e3bb.png)

The table `pgpubsub_notification` exists
![image](https://user-images.githubusercontent.com/809712/215849257-f7fb52b6-2e1e-4e3c-b339-a71f3b3ba4de.png)

And the migration is also on `django_migrations` table as applied.
![image](https://user-images.githubusercontent.com/809712/215849543-2183f7c8-eeec-4c40-94de-9f6a5a460894.png)

So, pretty weird indeed. 😅

**Comment by PaulGilmartin** [comment]
I don’t understand what the migration about altering the notification id is doing. Can you show me both of the migration files generated by pgpubsub?

**Comment by ricardoduarte** [comment]
I realized why it is asking to create migration every time I run the application, because as the migration is created outside app directorty it is not persisted when the container is removed, so every time I run the container again, it is asking for the file.

Here are the file contents:

0001_initial.py
```python
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=63)),
                ('payload', models.JSONField()),
            ],
        ),
    ]
```

0002_alter_notification_id.py
```python
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgpubsub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

**Comment by PaulGilmartin** [comment]
@ricardoduarte Ah ok, I guess the migration issue was a bit of a red herring then. I was also confused about the AlterField migration, but I'm thinking it has nothing to do with pgpubsub and could possibly be explained by your app settings(e.g. as explained in https://stackoverflow.com/questions/71118545/django-forcing-bigautofield-even-though-default-is-set-to-autofield).

I'm kind of back to square one in diagnosing your original issue now.  
Two things to possibly try:
1. What happens if you remove the "worker" step from docker-compose, you exec into the container created by the "web" step and then try the listen command in there?
2.  What happens if you try:
```
from django.db import connection
cursor = connection.cursor()
cursor.execute(f'LISTEN {SubmissionGroupClones.listen_safe_name()};')
```

**Comment by ricardoduarte** [comment]
@PaulGilmartin Thanks for the explanation about the migrations.
 
 About the solutions you suggested me to try:
 1. Already tried and got same error;
 2. Need to try but can't do it today. I'll try it tomorrow and get back to you with the result.
 
 Thank you so much for your attention and help with this issue.

**Comment by minsau** [comment]
I have same problem, when I execute the sentence 
```
cursor.execute(f'LISTEN {MyChannel.listen_safe_name()};')
```
It doesn't show something, I am inside a shell

In [1]: from api.channels import MyChannel

In [2]: from django.db import connection
   ...: cursor = connection.cursor()

In [3]: cursor.execute(f'LISTEN {MyChannel.listen_safe_name()};')

In [4]:

**Comment by minsau** [comment]
Maybe is something related with postgres configuration, should I install something in my postgres docker server?

**Comment by ricardoduarte** [comment]
Hello @minsau

If the command didn't show you anything, it means it worked fine. In my case, it is throwing an exception when the application reaches a line like this.

Tomorrow, I'll test this within a shell and post here the result.

**Comment by PaulGilmartin** [comment]
@minsau Yeah as @ricardoduarte points out, we shouldn't expect feedback when we execute the LISTEN statement from within the Django layer. If you want to get the feedback, you can do so directly in psql in your database postgres container (mine is called django-pgpubsub-db-1 and the user is called "postgres") :

```
docker exec -it django-pgpubsub-db-1 bash
root@6dc2d593f787:/# su - postgres
postgres@6dc2d593f787:~$ psql
postgres=# LISTEN test;
LISTEN
postgres=# NOTIFY test, 'this is the payload';
NOTIFY
Asynchronous notification "test" with payload "this is the payload" received from server process with PID 101.

```

**Comment by ricardoduarte** [comment]
@PaulGilmartin Tested `LISTEN` SQL statement as you asked above and it worked fine within Django shell.
```python
root@01320f3e90ce:/app# python manage.py shell
Python 3.9.16 (main, Jan 18 2023, 02:15:08)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.db import connection
>>> from submissions.channels import SubmissionGroupClones
>>> cursor = connection.cursor()
>>> cursor.execute(f'LISTEN {SubmissionGroupClones.listen_safe_name()};')
>>>
```

**Comment by PaulGilmartin** [comment]
@ricardoduarte Hmm, I wonder what's going wrong then. I even tried mimicking your listener/channel set up on my local machine and I could execute the `listen` command against the SubmissionGroupClones channel as expected:

```
    ~/Py/django-pgpubsub    master !8 ?5  docker compose up                                                                            ✔  13s   11:05:42  
[+] Running 0/1
 ⠙ Network django-pgpubsub_default  Creating                                                                                                                      0.1s
[+] Running 3/3d orphan containers ([django-pgpubsub_app_1]) for this project. If you removed or renamed this service in your compose file, you can run this command wi
 ⠿ Network django-pgpubsub_default  Created                                                                                                                       0.1s
 ⠿ Container django-pgpubsub-db-1   Created                                                                                                                       0.2s
 ⠿ Container django-pgpubsub-web-1  Created                                                                                                                       0.1s
Attaching to django-pgpubsub-db-1, django-pgpubsub-web-1
django-pgpubsub-db-1   | 
django-pgpubsub-db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
django-pgpubsub-db-1   | 
django-pgpubsub-db-1   | 2023-02-01 11:05:51.774 UTC [1] LOG:  starting PostgreSQL 12.12 (Debian 12.12-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
django-pgpubsub-db-1   | 2023-02-01 11:05:51.776 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
django-pgpubsub-db-1   | 2023-02-01 11:05:51.778 UTC [1] LOG:  listening on IPv6 address "::", port 5432
django-pgpubsub-db-1   | 2023-02-01 11:05:51.782 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
django-pgpubsub-db-1   | 2023-02-01 11:05:51.801 UTC [25] LOG:  database system was shut down at 2023-02-01 11:05:42 UTC
django-pgpubsub-db-1   | 2023-02-01 11:05:51.809 UTC [1] LOG:  database system is ready to accept connections
django-pgpubsub-web-1  | Listening on pgpubsub.tests.channels.SubmissionGroupClones
```

For context, my docker-compose file looks as follows:

```

version: '3.7'

services:
  web:    
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python /django-pgpubsub/manage.py listen
    volumes:
      - .:/django-pgpubsub
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ****
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

```
